exclude: 'build|docs|node_modules|.git|.tox|dist|docs|ai00i.egg-info'
default_stages: [commit]
fail_fast: true
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/petalmd/dockerfile-pre-commit
    rev: v1.0
    hooks:
    - id: dockerlint

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        args: ['--line-length', '120']

  - repo: https://github.com/windpioneers/pre-commit-hooks
    rev: 0.0.5
    hooks:
      - id: check-branch-name
        args:
          - '^main$'
          - '^development$'
          - '^devops/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          - '^doc/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          - '^feature/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          - '^fix/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          - '^hotfix/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          - '^review/([a-z][a-z0-9]*)(-[a-z0-9]+)*$'
          - '^release/(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
