FROM python:3.8

RUN mkdir -p /d/GitProjects/FORESEE_ETHZ_app//d/GitProjects/FORESEE_ETHZ_app/

WORKDIR /FORESEE_ETHZ/

COPY requirements.txt .

RUN pip3 install -r ./requirements.txt

COPY . .

CMD ["python3", "./train_traffic_intensity_RF_model.py"]
